export const ROUTES = {
  HOMEPAGE: "/",
  ADMIN_DASHBOARD: "/admin/dashboard",
  AUTH_LOGIN: "/auth/login",
  TEST: "/test",
  SETTINGS: "/admin/settings",
  USERS: "/admin/users",
  USER_ADD: "/admin/users/add",
  USER_EDIT: (id: string) => `/admin/users/edit/${id}`,
  OFFICES: "/admin/offices",
  OFFICE_ADD: "/admin/offices/add",
  OFFICE_EDIT: (id: string) => `/admin/offices/edit/${id}`,
  DEPARTMENTS: "/admin/departments",
  DEPARTMENT_ADD: "/admin/departments/add",
  DEPARTMENT_EDIT: (id: string) => `/admin/departments/edit/${id}`,
  DEVICE_TYPES: "/admin/device-types",
  DEVICE_TYPE_ADD: "/admin/device-types/add",
  DEVICE_TYPE_EDIT: (id: string) => `/admin/device-types/edit/${id}`,
  DEVICE_MODELS: "/admin/device-models",
  DEVICE_MODEL_ADD: "/admin/device-models/add",
  DEVICE_MODEL_EDIT: (id: string) => `/admin/device-models/edit/${id}`,
  ASSETS: "/admin/assets",
  ASSET_ADD: "/admin/assets/add",
  ASSET_EDIT: (id: string) => `/admin/assets/edit/${id}`,
  ASSET_CREATE_REQUEST: (id: string) => `/admin/assets/create-request/${id}`,
  ASSET_TRANSACTIONS: "/admin/asset-transactions",
  ASSET_TRANSFER_BATCHES: "/admin/asset-transfer-batches",
  ASSET_TRANSFER_BATCH_CONFIRM: (id: string) =>
    `/asset-transfer-batches/confirm/${id}?type=TRANSFER`,
  SUPPLIERS: "/admin/suppliers",
  SUPPLIER_ADD: "/admin/suppliers/add",
  SUPPLIER_EDIT: (id: string) => `/admin/suppliers/edit/${id}`,
};
